name:                bmm-simulate
version:             0.1.0.0
github:              "dschrempf/bmm-simulate"
license:             BSD3
author:              "Dominik Schrempf"
maintainer:          "dominik.schrempf@gmail.com"
copyright:           "Dominik Schrempf (2018)"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/dschrempf/bmm-simulate#readme>

ghc-options:
        - -Wall
        - -Werror

dependencies:
- ansi-wl-pprint >= 0.6.7.3
- attoparsec >= 0.13.1.0
- base >= 4.7 && < 5
- distribution >= 1.1.1.0
- hmatrix >= 0.18.0.0
- integration >= 0.2.1
- monad-logger
- optparse-applicative >= 0.13.2.0
- random >= 1.1
- random-fu >= 0.2.7.0
- statistics >= 0.13.3.0
- text >= 1.2.2.1
- transformers
- vector >= 0.11.0.0
- MonadRandom >= 0.5.1
- bytestring >= 0.10.8.1
- zlib >= 0.6.1.2

library:
  source-dirs: src

executables:
  bmm-simulate:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -eventlog
    - -O2
    dependencies:
    - bmm-simulate

tests:
  bmm-simulate-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - bmm-simulate
